github-enterprise:
  baseUrl: ${GITHUB_ENTERPRISE_BASE_URL:}
  githubAppId: ${GITHUB_APP_ID:}
  pemFile: ${PEM_FILE:}
  manifestFileDirectory: ${MANIFEST_FILE_DIRECTORY:}
  webhookSecret: ${WEBHOOK_SECRET:}
leanix:
  base-url: https://${LEANIX_DOMAIN}/services
  ws-base-url: wss://${LEANIX_DOMAIN}/services/git-integrations/v1/git-ws
  auth:
    access-token-uri: ${leanix.base-url}/mtm/v1
    technical-user-token: ${LEANIX_TECHNICAL_USER_TOKEN}
webhookEventService:
  waitingTime: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1000
