name: blackduck-scan

concurrency:
  group: blackduck-scan-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *
  push:
    branches:
      - feature/CID-3003/Implement-SAP-security-tooling

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --depth=1
      - name: Setup Java 21
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version: 21
      - run: echo "project_version=0.0.3" >> $GITHUB_ENV
      - name: Blackduck Scan
        uses: SAP/project-piper-action@27cadf261545552a68660531476c0915a97ee3d8
        with:
          command: detectExecuteScan
          flags: \
            --version=$PROJECT_VERSION \
            --excludedDirectories=test-packages
        env:
          PIPER_token: ${{ secrets.BLACKDUCK_TOKEN }}
          PROJECT_VERSION: ${{ env.project_version }}
          DETECT_TIMEOUT: 6000
          DETECT_YARN_EXCLUDED_WORKSPACES: test-packages/**
          DETECT_YARN_DEPENDENCY_TYPES_EXCLUDED: NON_PRODUCTION
