name: Build and test

concurrency:
  group: gradle-build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  validation:
    name: Branch name validation
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || \
            [[ "${{ github.ref }}" =~ ^refs/heads/feature/.*$ ]] || \
            [[ "${{ github.ref }}" =~ ^refs/heads/release/v.*$ ]] || \
            [[ "${{ github.ref }}" =~ ^refs/heads/bug/.*$ ]] || \
            [[ "${{ github.ref }}" == "refs/heads/renovate/all-dependencies" ]] ; then
            echo "Branch naming is correct!"
          else
            echo "Invalid branch name! Correct format: 'feature/<branch-name>' or 'bug/<branch-name>' or release/vx.x.x"
            exit 1
          fi
  gradle-ci:
    name: Build and test
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Setup Java
        uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0
        continue-on-error: false
        with:
          arguments: build