name: leanix-github-agent-code-coverage

concurrency:
  group: leanix-github-agent-code-coverage-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  leanix-github-agent-connector-ci:
    name: Build and test LeanIX GitHub Agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Setup Java
        uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0
        id: gradle-build
        continue-on-error: false
        with:
          arguments: build
          build-root-directory: .

      - name: Report Test Results
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        with:
          name: Unit Tests
          path: |
            ${{ github.workspace }}/build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: true
          only-summary: false

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@db72e7e7c96f98d239967958b0a0a6ca7d3bb45f # v1.6.1
        with:
          paths: ${{ github.workspace }}/build/jacocoXml/jacocoTestReport.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: LeanIX GitHub Agent Code Coverage
          update-comment: true

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
