name: Publish Package to ghcr.io

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    environment: ghcr:leanix-github-agent

    steps:
      - name: Extract Docker image tag
        id: extract_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          CLEAN_TAG=${TAG//[^0-9.]/}
          echo "Docker image tag: ${CLEAN_TAG}"
          echo "::set-output name=tag::${CLEAN_TAG}"

      - name: Checkout
        uses: actions/checkout@v3
        if: (steps.tag-action.outputs.tag != '')

      - name: Setup Java
        uses: actions/setup-java@v3
        if: (steps.tag-action.outputs.tag != '')
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        if: (steps.tag-action.outputs.tag != '')
        continue-on-error: false
        with:
          arguments: build

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
